### ISSUE TITLE
Generalization to decoder-only models

### ISSUE THREAD

**Issue by SoumiDas** [benzakenelad/BitFit#4]
Hi,

I was wondering if you could give your opinion on how well would BitFit generalize to decoder-only models? In case you already have tried out some experiments, it would be great to have some insights on them.

Regards,

**Comment by benzakenelad** [comment]
Hi,

Many papers have tried BitFit for decoder-only models, vision models,
speech models, and RL models. AFAIK it generalizes quite well for all of
them.

Good luck.

**Comment by benzakenelad** [comment]
.
